---
- name: Display help information
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Display help information
      ansible.builtin.debug:
        msg: |
          Usage: ansible-playbook evernode/config_xahaud-fallback.yml -e "nodes=<value> [xahaud_fallback=<value>]"

          Description:
            This playbook will display or configure xahaud-fallback. Note! You can enter more than one xahaud-fallback server, space separated. Also note the variable is xahaud_fallback because of how ansible interprets the hyphen.

          Options:
            - nodes: Required. Use "evernode" for the group or specify one or more individual nodes "evr-node02,evr-node05". Dependent on how you set up your /etc/ansible/hosts file.
            - xahaud_fallback: Optional. If not specified, return current xahaud-fallback values. If specified, configure node to use new xahaud-fallback server(s).

          Example:
            ansible-playbook evernode/config_xahaud-fallback.yml -e "nodes=evernode" will show the current xahaud-fallback for the group "evernode" as defined in /etc/ansible/hosts.
            ansible-playbook evernode/config_xahaud-fallback.yml -e "nodes=evr-node02,evr-node05 xahaud_fallback=wss://xahau.network,wss://xahau02.network" will configure the xahaud-fallback on those two nodes only to use websockets wss://xahau.network and wss://xahau02.network.
  tags: [help]

- name: config xahaud-fallback
  hosts: "{{ nodes | default('localhost') }}"
  gather_facts: no
  become: true
  tags: [main]

  tasks:
    - name: run evernode config xahaud-fallback
      ansible.builtin.command: evernode config "xahaud-fallback" "{{ xahaud_fallback | default('') }}"
      register: command_output
      when: "'help' not in (ansible_run_tags | default([]))"

    - name: show output
      debug:
        var: command_output.stdout_lines
      when: "'help' not in (ansible_run_tags | default([]))"
