---
- name: Display help information
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Display help information
      ansible.builtin.debug:
        msg: |
          Usage: ansible-playbook evernode/status.yml -e "nodes=<value>"

          Description:
            This playbook will display current status.

          Options:
            - nodes: Required. Use "evernode" for the group or specify one or more individual nodes "evr-node02,evr-node05". Dependent on how you set up your /etc/ansible/hosts file.

          Example:
            ansible-playbook evernode/status.yml -e "nodes=evernode" will show the current status for the group "evernode" as defined in /etc/ansible/hosts.
  tags: [help]

- name: status
  hosts: "{{ nodes | default('localhost') }}"
  gather_facts: no
  become: true
  tags: [main]

  tasks:
    - name: run evernode status
      ansible.builtin.command: evernode status
      register: command_output
      when: "'help' not in (ansible_run_tags | default([]))"

    - name: show output
      debug:
        var: command_output.stdout_lines
      when: "'help' not in (ansible_run_tags | default([]))"
